# docker-compose.yml


services:
  app:
<<<<<<< Updated upstream
	build:
	  context: .
	  dockerfile: Dockerfile.app
	ports:
	  - "8000:8000"
	volumes:
	  # CHANGE THIS LINE:
	  # Old: - COSC450DB:/usr/src/app/database
	  - COSC450DB:/usr/src/app/data # Align with Dockerfile and Server path

volumes:
  COSC450DB:
=======
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      # CHANGE THIS LINE:
      # Old: - COSC450DB:/usr/src/app/database
      - COSC450DB:/usr/src/app/data # Align with Dockerfile and Server path

volumes:
  COSC450DB:
>>>>>>> Stashed changes
